### ISSUE TITLE
`jeremyleo/postgres-2k-cube` docker image

### ISSUE THREAD

**Issue by LearningBunn** [jeremyleonardo/insightface-api#8]
Hi @jeremyleonardo , i come across your repo lately, can I know what is the docker file you use to build `jeremyleo/postgres-2k-cube` docker image? Because I try to mount the volume from the database to my local but I fail to do so, can you show me you docker file to build the `jeremyleo/postgres-2k-cube` docker image and how to set or find out where will the database store in the docker container created?

**Comment by jeremyleonardo** [comment]
@LearningBunn Hi, you can see the dockerfile at https://github.com/jeremyleonardo/postgres-2k-cube/blob/main/Dockerfile
